#!/bin/bash
echo "Building Base Packages"

sudo apt-get install libsdl-image1.2-dev
sudo apt-get install libsdl-dev

# build heartbeat
catkin_make --pkg heartbeat

# build localization package
catkin_make --pkg gps_common

# build task packages 
catkin_make --pkg wamv_bringup

# build remaining packages
catkin_make

# source bash file
source devel/setup.bash