// Generated by gencpp from file heartbeat/detectDeliver.msg
// DO NOT EDIT!


#ifndef HEARTBEAT_MESSAGE_DETECTDELIVER_H
#define HEARTBEAT_MESSAGE_DETECTDELIVER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heartbeat
{
template <class ContainerAllocator>
struct detectDeliver_
{
  typedef detectDeliver_<ContainerAllocator> Type;

  detectDeliver_()
    : msgID()
    , date()
    , time()
    , teamID()
    , shapeColor()
    , shape()
    , checksum(0)  {
    }
  detectDeliver_(const ContainerAllocator& _alloc)
    : msgID(_alloc)
    , date(_alloc)
    , time(_alloc)
    , teamID(_alloc)
    , shapeColor(_alloc)
    , shape(_alloc)
    , checksum(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msgID_type;
  _msgID_type msgID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _date_type;
  _date_type date;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _time_type;
  _time_type time;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _teamID_type;
  _teamID_type teamID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shapeColor_type;
  _shapeColor_type shapeColor;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shape_type;
  _shape_type shape;

   typedef int32_t _checksum_type;
  _checksum_type checksum;





  typedef boost::shared_ptr< ::heartbeat::detectDeliver_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heartbeat::detectDeliver_<ContainerAllocator> const> ConstPtr;

}; // struct detectDeliver_

typedef ::heartbeat::detectDeliver_<std::allocator<void> > detectDeliver;

typedef boost::shared_ptr< ::heartbeat::detectDeliver > detectDeliverPtr;
typedef boost::shared_ptr< ::heartbeat::detectDeliver const> detectDeliverConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heartbeat::detectDeliver_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heartbeat::detectDeliver_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace heartbeat

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'heartbeat': ['/home/dasc/Downloads/RobotX/robotrepo/RobotX_WS/src/heartbeat/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::heartbeat::detectDeliver_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heartbeat::detectDeliver_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heartbeat::detectDeliver_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heartbeat::detectDeliver_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heartbeat::detectDeliver_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heartbeat::detectDeliver_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heartbeat::detectDeliver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce0c58613dee387ebf511525a16db3e0";
  }

  static const char* value(const ::heartbeat::detectDeliver_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce0c58613dee387eULL;
  static const uint64_t static_value2 = 0xbf511525a16db3e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::heartbeat::detectDeliver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heartbeat/detectDeliver";
  }

  static const char* value(const ::heartbeat::detectDeliver_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heartbeat::detectDeliver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msgID\n\
string date\n\
string time\n\
string teamID\n\
string shapeColor\n\
string shape\n\
int32 checksum\n\
";
  }

  static const char* value(const ::heartbeat::detectDeliver_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heartbeat::detectDeliver_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msgID);
      stream.next(m.date);
      stream.next(m.time);
      stream.next(m.teamID);
      stream.next(m.shapeColor);
      stream.next(m.shape);
      stream.next(m.checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detectDeliver_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heartbeat::detectDeliver_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heartbeat::detectDeliver_<ContainerAllocator>& v)
  {
    s << indent << "msgID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msgID);
    s << indent << "date: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.date);
    s << indent << "time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.time);
    s << indent << "teamID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.teamID);
    s << indent << "shapeColor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shapeColor);
    s << indent << "shape: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shape);
    s << indent << "checksum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEARTBEAT_MESSAGE_DETECTDELIVER_H
