// Generated by gencpp from file heartbeat/entranceExit.msg
// DO NOT EDIT!


#ifndef HEARTBEAT_MESSAGE_ENTRANCEEXIT_H
#define HEARTBEAT_MESSAGE_ENTRANCEEXIT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heartbeat
{
template <class ContainerAllocator>
struct entranceExit_
{
  typedef entranceExit_<ContainerAllocator> Type;

  entranceExit_()
    : msgID()
    , date()
    , time()
    , teamID()
    , entrGate(0)
    , exitGate(0)
    , buoyActive()
    , lightPat()
    , checksum(0)  {
    }
  entranceExit_(const ContainerAllocator& _alloc)
    : msgID(_alloc)
    , date(_alloc)
    , time(_alloc)
    , teamID(_alloc)
    , entrGate(0)
    , exitGate(0)
    , buoyActive(_alloc)
    , lightPat(_alloc)
    , checksum(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msgID_type;
  _msgID_type msgID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _date_type;
  _date_type date;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _time_type;
  _time_type time;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _teamID_type;
  _teamID_type teamID;

   typedef int32_t _entrGate_type;
  _entrGate_type entrGate;

   typedef int32_t _exitGate_type;
  _exitGate_type exitGate;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _buoyActive_type;
  _buoyActive_type buoyActive;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lightPat_type;
  _lightPat_type lightPat;

   typedef int32_t _checksum_type;
  _checksum_type checksum;





  typedef boost::shared_ptr< ::heartbeat::entranceExit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heartbeat::entranceExit_<ContainerAllocator> const> ConstPtr;

}; // struct entranceExit_

typedef ::heartbeat::entranceExit_<std::allocator<void> > entranceExit;

typedef boost::shared_ptr< ::heartbeat::entranceExit > entranceExitPtr;
typedef boost::shared_ptr< ::heartbeat::entranceExit const> entranceExitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heartbeat::entranceExit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heartbeat::entranceExit_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace heartbeat

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'heartbeat': ['/home/dasc/Downloads/RobotX/robotrepo/RobotX_WS/src/heartbeat/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::heartbeat::entranceExit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heartbeat::entranceExit_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heartbeat::entranceExit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heartbeat::entranceExit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heartbeat::entranceExit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heartbeat::entranceExit_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heartbeat::entranceExit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fee52aea8394473a9a7f6073941038c1";
  }

  static const char* value(const ::heartbeat::entranceExit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfee52aea8394473aULL;
  static const uint64_t static_value2 = 0x9a7f6073941038c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::heartbeat::entranceExit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heartbeat/entranceExit";
  }

  static const char* value(const ::heartbeat::entranceExit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heartbeat::entranceExit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msgID\n\
string date\n\
string time\n\
string teamID\n\
int32 entrGate\n\
int32 exitGate\n\
string buoyActive\n\
string lightPat\n\
int32 checksum\n\
";
  }

  static const char* value(const ::heartbeat::entranceExit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heartbeat::entranceExit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msgID);
      stream.next(m.date);
      stream.next(m.time);
      stream.next(m.teamID);
      stream.next(m.entrGate);
      stream.next(m.exitGate);
      stream.next(m.buoyActive);
      stream.next(m.lightPat);
      stream.next(m.checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct entranceExit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heartbeat::entranceExit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heartbeat::entranceExit_<ContainerAllocator>& v)
  {
    s << indent << "msgID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msgID);
    s << indent << "date: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.date);
    s << indent << "time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.time);
    s << indent << "teamID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.teamID);
    s << indent << "entrGate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.entrGate);
    s << indent << "exitGate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.exitGate);
    s << indent << "buoyActive: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.buoyActive);
    s << indent << "lightPat: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lightPat);
    s << indent << "checksum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEARTBEAT_MESSAGE_ENTRANCEEXIT_H
