// Generated by gencpp from file heartbeat/finalMsg.msg
// DO NOT EDIT!


#ifndef HEARTBEAT_MESSAGE_FINALMSG_H
#define HEARTBEAT_MESSAGE_FINALMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heartbeat
{
template <class ContainerAllocator>
struct finalMsg_
{
  typedef finalMsg_<ContainerAllocator> Type;

  finalMsg_()
    : message()  {
    }
  finalMsg_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::heartbeat::finalMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heartbeat::finalMsg_<ContainerAllocator> const> ConstPtr;

}; // struct finalMsg_

typedef ::heartbeat::finalMsg_<std::allocator<void> > finalMsg;

typedef boost::shared_ptr< ::heartbeat::finalMsg > finalMsgPtr;
typedef boost::shared_ptr< ::heartbeat::finalMsg const> finalMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heartbeat::finalMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heartbeat::finalMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace heartbeat

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'heartbeat': ['/home/dasc/Downloads/RobotX/robotrepo/RobotX_WS/src/heartbeat/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::heartbeat::finalMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heartbeat::finalMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heartbeat::finalMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heartbeat::finalMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heartbeat::finalMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heartbeat::finalMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heartbeat::finalMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::heartbeat::finalMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::heartbeat::finalMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heartbeat/finalMsg";
  }

  static const char* value(const ::heartbeat::finalMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heartbeat::finalMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n\
";
  }

  static const char* value(const ::heartbeat::finalMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heartbeat::finalMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct finalMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heartbeat::finalMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heartbeat::finalMsg_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEARTBEAT_MESSAGE_FINALMSG_H
