#!/bin/bash
echo "Building localization Packages"
sudo apt-get install ros-kinetic-robot-localization
sudo apt-get install ros-kinetic-cost*
sudo apt-get install ros-kinetic-navigation*

# build heartbeat
catkin_make --pkg wamv_autonomy

# build remaining packages
catkin_make

# source bash file
source devel/setup.bash