#!/bin/bash
# build heartbeat
catkin_make --pkg heartbeat

# build imu tools
catkin_make --pkg imu_tools

# build localization package
catkin_make --pkg gps_common

# build task packages 
catkin_make --pkg wamv_bringup

# build simulator
catkin_make --pkg kingfisher_description robotx_gazebo wamv_description

# build task packages 
catkin_make --pkg wamv_autonomy

# build remaining packages
catkin_make

# confirm build
catkin_make

# source bash file
source devel/setup.bash

# confirm build
catkin_make
