// Generated by gencpp from file waypoint_follower_pid/TuningParameters.msg
// DO NOT EDIT!


#ifndef WAYPOINT_FOLLOWER_PID_MESSAGE_TUNINGPARAMETERS_H
#define WAYPOINT_FOLLOWER_PID_MESSAGE_TUNINGPARAMETERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waypoint_follower_pid
{
template <class ContainerAllocator>
struct TuningParameters_
{
  typedef TuningParameters_<ContainerAllocator> Type;

  TuningParameters_()
    : out_x(0.0)
    , out_v(0.0)
    , err_v(0.0)  {
    }
  TuningParameters_(const ContainerAllocator& _alloc)
    : out_x(0.0)
    , out_v(0.0)
    , err_v(0.0)  {
  (void)_alloc;
    }



   typedef float _out_x_type;
  _out_x_type out_x;

   typedef float _out_v_type;
  _out_v_type out_v;

   typedef float _err_v_type;
  _err_v_type err_v;





  typedef boost::shared_ptr< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> const> ConstPtr;

}; // struct TuningParameters_

typedef ::waypoint_follower_pid::TuningParameters_<std::allocator<void> > TuningParameters;

typedef boost::shared_ptr< ::waypoint_follower_pid::TuningParameters > TuningParametersPtr;
typedef boost::shared_ptr< ::waypoint_follower_pid::TuningParameters const> TuningParametersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace waypoint_follower_pid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'waypoint_follower_pid': ['/home/wamv/Documents/robotrepo/RobotX_WS/src/waypoint_follower_pid/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0980976f0bdca75f72b664cc976a51bc";
  }

  static const char* value(const ::waypoint_follower_pid::TuningParameters_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0980976f0bdca75fULL;
  static const uint64_t static_value2 = 0x72b664cc976a51bcULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoint_follower_pid/TuningParameters";
  }

  static const char* value(const ::waypoint_follower_pid::TuningParameters_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Tuning message\n\
float32 out_x\n\
float32 out_v\n\
float32 err_v\n\
";
  }

  static const char* value(const ::waypoint_follower_pid::TuningParameters_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.out_x);
      stream.next(m.out_v);
      stream.next(m.err_v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TuningParameters_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoint_follower_pid::TuningParameters_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoint_follower_pid::TuningParameters_<ContainerAllocator>& v)
  {
    s << indent << "out_x: ";
    Printer<float>::stream(s, indent + "  ", v.out_x);
    s << indent << "out_v: ";
    Printer<float>::stream(s, indent + "  ", v.out_v);
    s << indent << "err_v: ";
    Printer<float>::stream(s, indent + "  ", v.err_v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINT_FOLLOWER_PID_MESSAGE_TUNINGPARAMETERS_H
